version: '3'
services:

  postgre_db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: hyy19960529

  mongo_db:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null

  amqp_service:
    image: "rabbitmq:3.7.4"
    ports: 
      - "15672:15672"

  api_gateway:
    image: twitter_gateway_service
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        delay: "1s"
        condition: on-failure

  auth_service:
    image: twitter_auth_service
    deploy:
      replicas: 1
      restart_policy:
        delay: "1s"
        condition: on-failure

  email_service:
    image: twitter_email_service
    deploy:
      replicas: 1
      restart_policy: 
        delay: "1s"
        condition: on-failure

  profile_service:
    image: twitter_profile_service
    deploy:
      replicas: 1
      restart_policy:
        delay: "1s"
        condition: on-failure

  tweet_service:
    image: twitter_tweet_service
    deploy:
      replicas: 1
      restart_policy:
        delay: "1s"
        condition: on-failure
