version: '3'
services:
  ## Router
  mongo_db:
    image: richackard/twitter_mongo_db
    deploy: 
      restart_policy: 
        condition: on-failure
    networks: 
      - twinet  


  postgre_db:
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hyy19960529
    networks: 
      - twinet            

  amqp_service:
    image: "rabbitmq:3.7.4-management"
    ports: 
      - "5672:5672"
      - "8081:15672"      
    networks: 
      - twinet 

  api_gateway:
    image: richackard/twitter_gateway_service
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet 
    depends_on:
      - amqp_service

  auth_service:
    image: richackard/twitter_auth_service
    deploy:
      replicas: 3
      restart_policy:
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet 
    depends_on:
      - amqp_service
      - mongo_db

  email_service:
    image: richackard/twitter_email_service
    deploy:
      replicas: 1
      restart_policy: 
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet
    depends_on:
      - amqp_service 

  profile_service:
    image: richackard/twitter_profile_service
    deploy:
      replicas: 2
      restart_policy:
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet
    depends_on:
      - amqp_service
      - mongo_db 

  tweet_service:
    image: richackard/twitter_tweet_service
    deploy:
      replicas: 3
      restart_policy:
        delay: "1s"
        condition: on-failure
    networks: 
      - twinet
    depends_on:
      - amqp_service
      - mongo_db

networks: 
  twinet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
