apiVersion: v1
kind: ReplicationController
metadata:
  name: memcached
  labels:
    role: memcached
    mode: standalone
spec:
  replicas: 1
  selector:
    role: memcached
    mode: standalone
  template:
    metadata:
      labels:
        role: memcached
        mode: standalone
    spec:
      containers:
      - name: memcached
        image: "memcached:1.5.7"
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcache-memcached
  labels:
    name: memcached
spec:
  ports:
  - port: 11211
    targetPort: 11211
    protocol: TCP
  selector:
    role: memcached
    mode: standalone