apiVersion: v1
kind: Service
metadata:
  name: mongodb-node01
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: mongo-db

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db-service
          image: mongo:3.6
          ports:
            - containerPort: 27017
          args:
          - "--port=27017"
          - "--bind_ip=0.0.0.0"