apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus-server
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30003
  selector:
    app: prometheus-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus
          args:
            - "-config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090