apiVersion: v1
kind: Service
metadata:
  name: mongodb-node02 
  labels:
    app: mongodb-node02
    role: mongoshard
    tier: backend
spec:
  selector:
    app: mongodb-shard-node02
    role: mongoshard
    tier: backend 
  ports:
