apiVersion: v1
kind: Service
metadata:
  name: mongodb-node04 
  labels:
    app: mongodb-node04
    role: mongoshard
    tier: backend
spec:
  selector:
    app: mongodb-shard-node04
    role: mongoshard
    tier: backend 
  ports:
