---
- hosts: witter-workers
  remote_user: ubuntu
  gather_facts: False
  become: yes

  tasks:
    - name: Join Swarm
      raw: docker swarm join --token SWMTKN-1-1mm73iekjz74v1i5pgy0rwnxvuo400k16y8fmjakkq5zu67z92-253zbrhv08l6snmp4k73nnxx6 10.0.1.6:2377
