---
- hosts: mongo-cluster
  remote_user: ubuntu
  gather_facts: False
  become: yes

  tasks:
    - name: Key.
      raw: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

    - name: Add Repo.
      raw: echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-3.4.list

    - name: Update Cache
      raw: sudo apt-get update

    - name: Install MongoDB
      raw: sudo apt-get install mongodb-org
